package com.antenapro.hotelcheck.analysis;

public enum HospitalityAnalysisDimension {
    HOTEL_IDENTITY_AND_PROPERTY_UNDERSTANDING,
    DISCOVERABILITY_AND_NAVIGATION,
    ROOMS_AND_ROOM_INFORMATION,
    AMENITIES_AND_GUEST_FACING_INFORMATION,
    CONTACT_AND_LOCATION,
    BOOKING_DISCOVERABILITY_AND_JOURNEY_SIGNALS,
    TRUST_AND_CLARITY,
    MOBILE_AND_TECHNICAL_GUEST_EXPERIENCE,
    SEO_AND_STRUCTURED_DATA_SUPPORTING_SIGNALS
}
