package com.antenapro.hotelcheck.analysis;

public enum RecommendationCategory {
    IMPROVE_BOOKING_DISCOVERABILITY,
    IMPROVE_ROOM_INFORMATION,
    IMPROVE_GUEST_FACING_INFORMATION,
    IMPROVE_CONTACT_LOCATION_INFORMATION,
    RESOLVE_INFORMATION_CONFLICT,
    IMPROVE_TRUST_CLARITY
}
